name: QA Test prod after merge

on: [workflow_dispatch, push]

jobs:
  Prod-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Cypress
        uses: bahmutov/npm-install@v1
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: electron
          spec: cypress/e2e/login.cy.js
        env:
          CYPRESS_allure=true
          PASSWORD=${{secrets.PRODUCTION_PASSWORD}}
          URL=${{secrets.PRODUCTION_URL}}
          AUTHNAME='${{secrets.PRODUCTION_AUTHNAME}}'
          USERNAME=${{secrets.PRODUCTION_USERNAME}}

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: allure
          github_run_num: "prod"

      #      - name: Clear report allure-results
      #        run: |
      #          sudo chown -R $USER:$USER ${{ github.workspace }}
      #          sudo npm run allure:clear
      #
      #      - name: Run Cypress
      #        continue-on-error: true
      #        run: |
      #          DEBUG=allure-plugin* PASSWORD=${{secrets.RELEASE_PASSWORD}} URL=${{secrets.RELEASE_URL}} AUTHNAME='${{secrets.RELEASE_AUTHNAME}}' USERNAME=${{secrets.RELEASE_USERNAME}} npx cypress run --env allure=true --browser chrome
      #
      #      - name: Test marketplace action
      #        uses: simple-elf/allure-report-action@master
      #        if: always()
      #        id: allure-report
      #        with:
      #          allure_results: allure-results
      #          allure_report: allure-report
      #          allure_history: ./allure-history/release

      #       - name: Deploy to GitHub Pages
      #         id: deployment
      #         uses: JamesIves/github-pages-deploy-action@4.2.0
      #         with:
      #           branch: gh-pages
      #           folder: ./allure-history

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: allure1.company-policy.com
          username: company-policy_1
          password: ${{ secrets.ftp_password }}
          local-dir: ./allure-history/
          server-dir: public_html/
          state-name: ../.ftp-deploy-sync-state.json

      - name: Show allure
        run: cat ./allure-history/index.html
