name: Test main

on: [workflow_dispatch]

jobs:
  Prod-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
          
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          spec: cypress/e2e/login.cy.js
        env: 
          CYPRESS_allure: true
          CYPRESS_USERNAME: ${{secrets.RELEASE_USERNAME}}
          CYPRESS_PASSWORD: ${{secrets.RELEASE_PASSWORD}}
          CYPRESS_URL: ${{secrets.RELEASE_URL}}
          CYPRESS_AUTHNAME: '${{secrets.RELEASE_AUTHNAME}}'
          
        #   env:  DEBUG=allure-plugin*, PASSWORD=${{secrets.PRODUCTION_PASSWORD}}

      # - name: Install Cypress
      #   run: npx cypress install

      # - name: Run Cypress
      #   continue-on-error: true
      #   run: |
      #     DEBUG=allure-plugin* PASSWORD=${{secrets.PRODUCTION_PASSWORD}} URL=${{secrets.PRODUCTION_URL}} AUTHNAME='${{secrets.PRODUCTION_AUTHNAME}}' USERNAME=${{secrets.PRODUCTION_USERNAME}} npx cypress run --env allure=true --browser chrome




      # - name: Download Cypress
      #   uses: bahmutov/npm-install@v1
      #   env:
      #     CYPRESS_INSTALL_BINARY: 0

      # - name: Check Cypress cache
      #   run: |
      #     npx cypress cache path
      #     npx cypress cache list

      # - name: Install Cypress
      #   run: |
      #     npx cypress install
      #     npx cypress cache list
      # - name: Run Cypress
      #   continue-on-error: true
      #   run: |
      #     DEBUG=allure-plugin* PASSWORD=${{secrets.PRODUCTION_PASSWORD}} URL=${{secrets.PRODUCTION_URL}} AUTHNAME='${{secrets.PRODUCTION_AUTHNAME}}' USERNAME=${{secrets.PRODUCTION_USERNAME}} npx cypress run --env allure=true --browser chrome

      # - name: Get Allure history
      #   uses: actions/checkout@v2
      #   if: always()
      #   continue-on-error: true
      #   with:
      #     ref: allure
      #     path: allure
          
      # - name: mkdir
      #   run: mkdir prod

      # - name: Generate Allure Report
      #   uses: simple-elf/allure-report-action@master
      #   if: always()
      #   with:
      #     allure_results: allure-results
      #     gh_pages: allure
      #     allure_history: ./prod/tested2/

#      - name: Clear report allure-results
#        run: |
#          sudo chown -R $USER:$USER ${{ github.workspace }}
#          sudo npm run allure:clear
#
#      - name: Run Cypress
#        continue-on-error: true
#        run: |
#          DEBUG=allure-plugin* PASSWORD=${{secrets.RELEASE_PASSWORD}} URL=${{secrets.RELEASE_URL}} AUTHNAME='${{secrets.RELEASE_AUTHNAME}}' USERNAME=${{secrets.RELEASE_USERNAME}} npx cypress run --env allure=true --browser chrome
#
#      - name: Test marketplace action
#        uses: simple-elf/allure-report-action@master
#        if: always()
#        id: allure-report
#        with:
#          allure_results: allure-results
#          allure_report: allure-report
#          allure_history: ./allure-history/release

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: JamesIves/github-pages-deploy-action@4.2.0
      #   with:
      #     branch: gh-pages
      #     folder: ./prod

      # - name: Show allure
      #   run: cat ./allure-history/index.html
