name: QA Testing server

on: repository_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Cypress cache
        run: |
          npx cypress cache path
          npx cypress cache list
      - name: Install Cypress
        run: |
          npx cypress install
          npx cypress cache list
      - name: Run Cypress
        continue-on-error: true
        run: DEBUG=allure-plugin* npx cypress run --env allure=true --browser chrome
        env:
          CYPRESS_SPLIT_SPEC_API_KEY: '${{ secrets.SPLIT_SPEC_API_KEY }}'

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: allure
          path: allure

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: allure

      - name: Show allure
        run: cat ./allure-history/index.html
