name: QA Test prod after merge

on: [workflow_dispatch, push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download Cypress
        uses: bahmutov/npm-install@v1
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Check Cypress cache
        run: |
          npx cypress cache path
          npx cypress cache list

      - name: Install Cypress
        run: |
          npx cypress install
          npx cypress cache list
      - name: Run Cypress
        continue-on-error: true
        run: |
          DEBUG=allure-plugin* PASSWORD=${{secrets.EMAIL_PASSWORD}} npx cypress run --env allure=true --browser chrome

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: allure
          path: allure

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: allure

      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: ./allure-history

      - name: Show allure
        run: cat ./allure-history/index.html
