name: Test Release server

on: [workflow_dispatch]

jobs:
  test-Release:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # --- Установка Node и Yarn, чтобы версии совпадали с локальными ---
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # --- Подготовка истории Allure ---
      - name: Prepare Allure History
        run: |
          if [ -d allure-history ]; then
            mkdir -p allure-results/history
            cp -r allure-history/* allure-results/history/
          fi

      # --- Запуск Cypress с видео и скриншотами ---
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: cypress/e2e/**/*.cy.js
          record: false
          install-command: yarn
        env:
          CYPRESS_allure: true
          URL: ${{vars.RELEASE_URL}}
          EMAIL: ${{vars.RELEASE_USERNAME}}
          PASSWORD: ${{secrets.RELEASE_PASSWORD}}
          MAILSLURP_API_KEY: ${{secrets.MAILSLURP_API_KEY}}
          QA_TEST_LOGIN: ${{vars.QA_TEST_LOGIN}}
          QA_TEST_PASSWORD: ${{secrets.QA_TEST_PASSWORD}}

      # --- Генерация отчёта с историей ---
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-results/history
          keep_reports: 5

      # --- Сохраняем обновлённую историю для следующих прогонов ---
      - name: Update Allure History
        run: |
          rm -rf allure-history
          cp -r allure-report/history allure-history

      # --- FTP Deploy отчёта ---
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        if: always()
        with:
          server: allure.company-policy.com
          username: company-policy_1
          password: ${{ secrets.ftp_password }}
          local-dir: allure-report/
          server-dir: public_html/release/
          state-name: ../.release_ftp-deploy-sync-state.json
