name: Test Prod server

on: [workflow_dispatch]

jobs:
  test-Prod:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/**/*.cy.js
          install-command: yarn
        env:
          CYPRESS_allure: true
          URL: ${{vars.PRODUCTION_URL}}
          EMAIL: ${{vars.PRODUCTION_USERNAME}}
          PASSWORD: ${{secrets.PRODUCTION_PASSWORD}}
          MAIL_TRAP_TOKEN: ${{secrets.MAIL_TRAP_TOKEN}}
          QA_TEST_LOGIN: ${{vars.QA_TEST_LOGIN}}
          QA_TEST_PASSWORD: ${{secrets.QA_TEST_PASSWORD}}
          BITRIX24_SECRET_KEY: ${{secrets.BITRIX24_SECRET_KEY}}
          BITRIX24_URL: ${{vars.BITRIX24_URL}}
          BITRIX24_USER_ID: ${{vars.BITRIX24_USER_ID}}

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
#          gh_pages: gh-pages
          # github_run_num: "release"

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        if: always()
        with:
          server: allure.company-policy.com
          username: company-policy_1
          password: ${{ secrets.ftp_password }}
          local-dir: allure-report/
          server-dir: public_html/prod/
          state-name: ../.prod_ftp-deploy-sync-state.json
