name: Test Release server

on: [workflow_dispatch]

jobs:
  test-Release:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: cypress/e2e/**/*.cy.js
          install-command: yarn
        env:
          CYPRESS_allure: true
          URL: ${{vars.RELEASE_URL}}
          EMAIL: ${{vars.RELEASE_USERNAME}}
          PASSWORD: ${{secrets.RELEASE_PASSWORD}}
          MAILSLURP_API_KEY: ${{secrets.MAILSLURP_API_KEY}}
          QA_TEST_LOGIN: ${{vars.QA_TEST_LOGIN}}
          QA_TEST_PASSWORD: ${{secrets.QA_TEST_PASSWORD}}

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results      # Папка с результатами тестов
          allure_report: allure-report        # Папка для HTML-отчёта
          allure_history: allure-history      # Папка для истории предыдущих прогонов
          keep_reports: 5                     # Количество хранимых прогонов 

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        if: always()
        with:
          server: allure.company-policy.com
          username: company-policy_1
          password: ${{ secrets.ftp_password }}
          local-dir: allure-report/
          server-dir: public_html/release/
          state-name: ../.release_ftp-deploy-sync-state.json