name: QA Test Release server - old

on: [workflow_dispatch]

jobs:
  Release-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Cypress cache
        run: |
          npx cypress cache path
          npx cypress cache list

      - name: Install Cypress
        run: |
          npx cypress install
          npx cypress cache list

      - name: Run Cypress
        continue-on-error: true
        run: |
          DEBUG=allure-plugin* PASSWORD=${{secrets.RELEASE_PASSWORD}} URL=${{secrets.RELEASE_URL}} AUTHNAME='${{secrets.RELEASE_AUTHNAME}}' USERNAME=${{secrets.RELEASE_USERNAME}} npx cypress run --spec ./cypress/e2e/*.cy.js --env allure=true --browser chrome
     
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          # gh_pages: allure
          # github_run_num: "release"

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: allure.company-policy.com
          username: company-policy_1
          password: ${{ secrets.ftp_password }}
          local-dir: ./allure-history/
          server-dir: public_html/release/
          state-name: ../.release_ftp-deploy-sync-state.json
