name: QA Test Production server

on: [workflow_dispatch]

jobs:
  Prod-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Cypress
        uses: bahmutov/npm-install@v1

      - name: Install Cypress
        run: |
          npx cypress install
          npx cypress cache list
      - name: Run Cypress
        continue-on-error: true
        run: |
          DEBUG=allure-plugin* PASSWORD=${{secrets.PRODUCTION_PASSWORD}} URL=${{secrets.PRODUCTION_URL}} AUTHNAME='${{secrets.PRODUCTION_AUTHNAME}}' USERNAME=${{secrets.PRODUCTION_USERNAME}} npx cypress run --spec ./cypress/e2e/*.cy.js --env allure=true --browser chrome
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: allure
          github_run_num: "prod"

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: allure.company-policy.com
          username: company-policy_1
          password: ${{ secrets.ftp_password }}
          local-dir: ./allure-history/
          server-dir: public_html/
          state-name: /.ftp-deploy-sync-state.json