name: Test Release server

on: [workflow_dispatch]

jobs:
  test-Release:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Используем ту же версию Node.js, что и локально
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      # Установка Yarn нужной версии
      - name: Setup Yarn
        run: npm install -g yarn@1.22.22

      - name: Install dependencies
        run: yarn install

      # Запуск Cypress с видео и Allure
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: cypress/e2e/**/*.cy.js
          record: false
          config: video=true
        env:
          CYPRESS_allure: true
          URL: ${{vars.RELEASE_URL}}
          EMAIL: ${{vars.RELEASE_USERNAME}}
          PASSWORD: ${{secrets.RELEASE_PASSWORD}}
          MAILSLURP_API_KEY: ${{secrets.MAILSLURP_API_KEY}}
          QA_TEST_LOGIN: ${{vars.QA_TEST_LOGIN}}
          QA_TEST_PASSWORD: ${{secrets.QA_TEST_PASSWORD}}

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
#          gh_pages: gh-pages
          # github_run_num: "release"

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        if: always()
        with:
          server: allure.company-policy.com
          username: company-policy_1
          password: ${{ secrets.ftp_password }}
          local-dir: allure-report/
          server-dir: public_html/prod/
          state-name: ../.prod_ftp-deploy-sync-state.json


          