name: Test Release server

on: [workflow_dispatch, push]

jobs:
  test-Prod:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
          
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          spec: cypress/e2e/**/*.cy.js
        env:
          CYPRESS_allure: true
          URL: ${{secrets.PRODUCTION_URL}}
          CYPRESS_username: ${{secrets.PRODUCTION_USERNAME}}
          CYPRESS_password: ${{secrets.PRODUCTION_PASSWORD}}
          CYPRESS_AUTHNAME: '${{secrets.PRODUCTION_AUTHNAME}}'

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
#          gh_pages: gh-pages
          # github_run_num: "release"

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        if: always()
        with:
          server: allure.company-policy.com
          username: company-policy_1
          password: ${{ secrets.ftp_password }}
          local-dir: allure-report/
          server-dir: public_html/prod/
          state-name: ../.prod_ftp-deploy-sync-state.json