name: Test Release server

on: [workflow_dispatch]

jobs:
  test-Release:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Show all env variables
        run: printenv
          

      - name: Install dependencies
        run: yarn install

      - name: Check current directory
        run: pwd

      - name: List root directory files
        run: ls -la

      - name: List Cypress config file
        run: ls -la cypress.config.js || echo "cypress.config.js not found"

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
        env:
          CYPRESS_allure: true
          URL: ${{ vars.RELEASE_URL }}
          EMAIL: ${{ vars.RELEASE_USERNAME }}
          PASSWORD: ${{ secrets.RELEASE_PASSWORD }}

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        if: always()
        with:
          server: allure.company-policy.com
          username: company-policy_1
          password: ${{ secrets.ftp_password }}
          local-dir: allure-report/
          server-dir: public_html/release/
          state-name: ../.release_ftp-deploy-sync-state.json
